AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-datalake

  Sample SAM Template for sam-datalake

Parameters:
  S3BucketName:
    Type: String
    Description: S3 Bucket Name for storing the pipeline data.
  GlueTableName:
    Type: String
    Description: S3 Bucket Name for storing the pipeline data.
  GlueDatabaseName:
    Type: String
    Description: S3 Bucket Name for storing the pipeline data.

Globals:
  Function:
    Timeout: 300
    Runtime: python3.7

Resources:
  ProcessDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: process_data/
      Handler: process_data.lambda_handler

  GlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabaseName
      TableInput:
        Name: !Ref GlueTableName
        TableType: EXTERNAL_TABLE
        StorageDescriptor:
          Location: !Sub "s3://${S3BucketName}/${AWS::StackName}/RawData/"
          Columns:
            - Name: ticker_symbol
              Type: string
            - Name: sector
              Type: string
            - Name: change
              Type: double
            - Name: price
              Type: double
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          Compressed: false
          NumberOfBuckets: -1
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
            Parameters:
              serialization.format: "1"
          BucketColumns: []
          SortColumns: []
          StoredAsSubDirectories: false
          Parameters:
            classification: parquet
            typeOfData: file
            compressionType: none
        PartitionKeys:
          - Name: year
            Type: string
          - Name: month
            Type: string
          - Name: day
            Type: string
          - Name: hour
            Type: string
        Parameters:
          classification: parquet
          typeOfData: file
          compressionType: none

  DeliveryStream:
    DependsOn:
      - DeliveryPolicy
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !Join ["", ["arn:aws:s3:::", !Ref S3BucketName]]
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref DeliveryLogGroup
          LogStreamName: !Ref DeliveryLogStream
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 64
        CompressionFormat: UNCOMPRESSED
        ErrorOutputPrefix:
          !Join [
            "/",
            [
              !Ref AWS::StackName,
              "Error",
              "!{firehose:error-output-type}",
              "year=!{timestamp:YYYY}",
              "month=!{timestamp:MM}",
              "day=!{timestamp:dd}",
              "hour=!{timestamp:HH}",
              "",
            ],
          ]
        Prefix:
          !Join [
            "/",
            [
              !Ref AWS::StackName,
              "RawData",
              "year=!{timestamp:YYYY}",
              "month=!{timestamp:MM}",
              "day=!{timestamp:dd}",
              "hour=!{timestamp:HH}",
              "",
            ],
          ]
        RoleARN: !GetAtt DeliveryRole.Arn
        DataFormatConversionConfiguration:
          SchemaConfiguration:
            CatalogId: !Ref AWS::AccountId
            RoleARN: !GetAtt DeliveryRole.Arn
            DatabaseName: !Ref GlueDatabaseName
            TableName: !Ref GlueTable
            Region: !Ref AWS::Region
            VersionId: LATEST
          InputFormatConfiguration:
            Deserializer:
              OpenXJsonSerDe: {}
          OutputFormatConfiguration:
            Serializer:
              ParquetSerDe: {}
          Enabled: True
        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Type: Lambda
              Parameters:
                - ParameterName: LambdaArn
                  ParameterValue: !GetAtt ProcessDataFunction.Arn

  DeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ""
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": !Ref "AWS::AccountId"

  DeliveryPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Join ["-", [!Ref AWS::StackName, "Delivery"]]
      Roles:
        - !Ref DeliveryRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ""
            Effect: Allow
            Action:
              - "glue:GetTable"
              - "glue:GetTableVersion"
              - "glue:GetTableVersions"
            Resource: "*"
          - Sid: ""
            Effect: Allow
            Action:
              - "s3:AbortMultipartUpload"
              - "s3:GetBucketLocation"
              - "s3:GetObject"
              - "s3:ListBucket"
              - "s3:ListBucketMultipartUploads"
              - "s3:PutObject"
            Resource:
              - !Join ["", ["arn:aws:s3:::", !Ref S3BucketName]]
              - !Join ["", ["arn:aws:s3:::", !Ref S3BucketName, "*"]]
              - "arn:aws:s3:::%FIREHOSE_BUCKET_NAME%"
              - "arn:aws:s3:::%FIREHOSE_BUCKET_NAME%/*"
          - Sid: ""
            Effect: Allow
            Action:
              - "lambda:InvokeFunction"
              - "lambda:GetFunctionConfiguration"
            Resource:
              - !Join
                - ":"
                - - !GetAtt ProcessDataFunction.Arn
                  # - "$LATEST"
          - Sid: ""
            Effect: Allow
            Action: "logs:PutLogEvents"
            Resource:
              - !Join
                - ":"
                - - "arn:aws:logs"
                  - !Ref "AWS::Region"
                  - !Ref "AWS::AccountId"
                  - "log-group"
                  - !Ref DeliveryLogGroup
                  - !Ref DeliveryLogStream
                  - "*"
          - Sid: ""
            Effect: Allow
            Action:
              - "kinesis:DescribeStream"
              - "kinesis:GetShardIterator"
              - "kinesis:GetRecords"
              - "kinesis:ListShards"
            Resource:
              - !Join
                - ":"
                - - "arn:aws:kinesis"
                  - !Ref AWS::Region
                  - !Ref AWS::AccountId
                  - "stream/%FIREHOSE_STREAM_NAME%"
          - Sid: ""
            Effect: Allow
            Action:
              - "kms:Decrypt"
            Resource:
              - !Join
                - ":"
                - - "arn:aws:kms"
                  - !Ref AWS::Region
                  - !Ref AWS::AccountId
                  - "key/%SSE_KEY_ID%"
            Condition:
              StringEquals:
                "kms:ViaService": "kinesis.%REGION_NAME%.amazonaws.com"
              StringLike:
                "kms:EncryptionContext:aws:kinesis:arn": !Join
                  - ":"
                  - - "arn:aws:kinesis"
                    - "%REGION_NAME%"
                    - !Ref AWS::AccountId
                    - "stream/%FIREHOSE_STREAM_NAME%"

  DeliveryLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7

  DeliveryLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref DeliveryLogGroup

Outputs:
  DeliveryStreamArn:
    Description: "Kinesis Firehose Delivery Stream ARN"
    Value: !GetAtt DeliveryStream.Arn
  DeliveryStreamName:
    Description: "Kinesis Firehose Delivery Stream Name"
    Value: !Ref DeliveryStream
